config/routes.rb
Rails.application.routes.draw do
  # get 'users/index'

  # get 'users/new'

  # get 'users/edit'

  # get 'articles/index'

  # get 'articles/edit'
  
  # post 'articles/new'

  # get 'articles/show'

  # ROUTE STANDARD

  # get 'articles/edit', to: "articles#edit", as: :articles
  # ------------------------------------------------------

  get "sign_up" => "users#new", :as => "sign_up"
  resources :users

  # RESTFULL ROUTE
  root :to => "articles#index" 
  resources :articles
   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true,
						length: { minimum: 5 }
	validates :content, presence: true,
						length: { minimum: 10 }
	validates :status, presence: true

	scope :status_active, -> {where(status: 'active')}
	default_scope {where(status: 'active')}

	
end

app/models/user.rb
class User < ApplicationRecord
	include Humanizer
	require_human_on :create



	validates :username, presence: true, uniqueness: true
	validates :email, presence: true, uniqueness: true
	validates :password, presence: true, on: :create,
		length: { minimum: 5},
		confirmation: true

	attr_accessor :password
	before_save :add_salt_and_hash

	def add_salt_and_hash
		unless password.blank?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end	
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	# layout "articles"
  # instanisasi class harus sesuai nama kelas {tapi harus sama : article}
  def index
    @article = Article.all
  end

  def new
    @article = Article.new
  	
  end

   def edit
    @article = Article.find_by_id(params[:id])
  end

  def create
    @article = Article.new(params_artikel)
    if @article.save
    flash[:notice] = "Success Add Rows"
    redirect_to action: 'index'
  else
    flash[:notice] = "Error Add Rows"
    render 'new'
  end

  end

  def show
    @article = Article.find_by_id(params[:id])
  end



  def update
    @article = Article.find_by_id(params[:id])
    if @article.update(params_artikel)
      flash[:notice] = "Success Update Rows"
      redirect_to action: 'index'
    else
      flash[:notice] = "Error Update Rows"
      render 'edit'
    end
  end

  def destroy
    @article = Article.find_by_id(params[:id])

    if @article.destroy
      flash[:notice] = "Success Delete a Records"
      redirect_to action: 'index'
    else
      flash[:error] = "fails delete a records"
      redirect_to action: 'index'
    end

  end

  private
   def params_artikel
    params.require(:article).permit(:title, :content, :status)
  end  

 

  def list
  	  @artikel = Article.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@user = User.all
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params_user)
  	if @user.save
  		flash[:notice] = "Success Add Records"
  		redirect_to root_url
  	else
  		flash[:error] = "Data Not Valid"
  		render "new"
  	end
  end

  def edit
  end

  private 
  def params_user
  		params.require(:user).permit(:username, :email, :password, :humanizer_answer, :humanizer_question_id)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/articles.html.erb
<% content_for :list do %>
 This is the content for head
<% end %>

<h1>LIST</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
      <td></td>
    </tr>
  </thead>

  <tbody>
    <% @artikel.each do |article| %>
      <tr>
        <td><%= article.title %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/content.html.erb
<% content_for :main do %>
<p>HAIIi</p>
<% end %>
 <%= render "main" %>

app/views/articles/edit.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="nav navbar-nav">
      <li class="nav-item"><%= link_to 'Home', articles_path, class: 'btn btn-lg btn-primary' %></li>
      <li class="nav-item"><%= link_to 'Add Data', new_article_path, class: 'btn btn-lg btn-warning' %></li>
      
    </ul>
</nav>
<div class="container">
  <div class="content-wrapper">
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <!-- CONTENT HERE -->
          <!-- END OF CONTENT -->

           <h2>Selamat Datang</h2>
           <h5>Edit Data Artikel</h5>
                <%= form_for @article do |f| %>
                <div class="form-group">
                  <%= f.label :title %>
                  <%= f.text_field :title, class: 'form-control' %>
                 
                  
                </div>
                <div class="form-group">
                  <%= f.label :content %>
                  <%= f.text_area :content, cols: 20, rows: 10, class: 'form-control' %>
                  
                  
                </div>
                <div class="form-group">
                  <%= f.label :status %>
                  <%= f.radio_button :status, "active" %>
                  <%= label :artikel_status, 'active' %>
                  <%= f.radio_button :status, "non-active", :checked => true %>
                  <%= label :artikel_status, 'off' %>
                </div>
                <div class="form-group">
                    <%= f.submit :submit %>
                </div>
                <% end %>

                <%= link_to 'back', articles_path, class: 'btn btn-md btn-info'%>
               
        </div>
      </div>
    </section>
  </div>
</div>






  

app/views/articles/index.html.erb
<!DOCTYPE html>
<html>
<head>
   <title>List Data</title>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
		<ul class="nav navbar-nav">
			<li class="nav-item"><%= link_to 'Home', articles_path, class: 'btn btn-lg btn-primary' %></li>
			<li class="nav-item"><%= link_to 'Add Data', new_article_path, class: 'btn btn-lg btn-warning' %></li>
			<li class="nav-item"><%= link_to 'User', new_user_path, class: 'btn btn-lg btn-info' %></li>
		</ul>
</nav>
<div class="container">
	<div class="content-wrapper">
		<section class="content">
			<div class="row">
				<div class="col-md-12">
					<!-- CONTENT HERE -->
				      <%= yield :list %>
				      <!-- END OF CONTENT -->

					 <h2>Selamat Datang</h2>
				      <div class="jumbotron">
				      	<h1 class="display-4">Hello, world!</h1>
						<p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
						<hr class="my-4">
						<p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
						<p class="lead">
						<a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
						</p>
				      </div>

				      <!-- Data Artikel -->
				      <table class="table table-striped">
				      	<thead>
				      		<tr>
				      			<th>Title</th>
				      			<th>Content</th>
				      			<th>Status</th>
				      			<th>Action</th>
				      		</tr>
				      	</thead>
				      	<tbody>
				      		<% @article.each do |article| %>
				      		<tr>
				      			<td><%= article.title %></td>
				      			<td><%= article.content.truncate(80) %></td>
				      			<td><%= article.status %></td>
				      			<td><%= link_to 'Read More', article_path(article.id) %>

				      				<%= link_to 'Edit', edit_article_path(article.id) %>
				      				<%= link_to 'Delete', article_path(article.id), method: "Delete", data: {confirm: 'Delete this data ? '} %>
				      				
				      			</td>
	   				       <% end %>
				      		</tr>
				      	</tbody>
				      </table>
				      
				      	
				     
				</div>
			</div>
		</section>
	</div>
</div>
	
  
</body>
</html>

app/views/articles/new.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="nav navbar-nav">
      <li class="nav-item"><%= link_to 'Home', articles_path, class: 'btn btn-lg btn-primary' %></li>
      <li class="nav-item"><%= link_to 'Add Data', new_article_path, class: 'btn btn-lg btn-warning' %></li>
      
    </ul>
</nav>
<div class="container">
  <div class="content-wrapper">
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <!-- CONTENT HERE -->
          <!-- END OF CONTENT -->

           <h2>Selamat Datang</h2>
           <h5>Tambah Data Artikel</h5>
                <%= form_for (@article) do |f| %>
                <div class="form-group">
                  <%= f.label :title %>
                  <%= f.text_field :title, class: 'form-control' %>
                  <%= @article.errors[:title].first unless @article.errors[:title].blank? %>

                  
                </div>
                <div class="form-group">
                  <%= f.label :content %>
                  <%= f.text_area :content, cols: 20, rows: 10, class: 'form-control' %>
                  <%= @article.errors[:content].first unless @article.errors[:content].blank? %>
                  
                </div>
                <div class="form-group">
                  <%= f.label :status %>
                  <%= f.radio_button :status, "active" %>
                  <%= label :artikel_status, 'active' %>
                  <%= f.radio_button :status, "non-active", :checked => true %>
                  <%= label :artikel_status, 'off' %>
                </div>
                <div class="form-group">
                    <%= f.submit :submit %>
                </div>
                <% end %>

        </div>
      </div>
    </section>
  </div>
</div>






  

app/views/articles/show.html.erb
<!DOCTYPE html>
<html>
<head>
   <title>List Data</title>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
		<ul class="nav navbar-nav">
			<li class="nav-item"><%= link_to 'Home', articles_path, class: 'btn btn-lg btn-primary' %></li>
			<li class="nav-item"><%= link_to 'Add Data', new_article_path, class: 'btn btn-lg btn-warning' %></li>
			
		</ul>
</nav>
<div class="container">
	<div class="content-wrapper">
		<section class="content">
			<div class="row">
				<div class="col-md-12">
					<!-- CONTENT HERE -->
				      <%= yield :list %>
				      <!-- END OF CONTENT -->

					 <h3><%= @article.title %></h3>
					 <p><%= @article.content %></p>
					 <p><%= link_to 'back', articles_path, class: 'btn btn-md btn-info'%></p> 	
				     
				</div>
			</div>
		</section>
	</div>
</div>
	
  
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Latihan</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'main' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
    <%= yield %>

  </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
   <title>List Data</title>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
		<ul class="nav navbar-nav">
			<li class="nav-item"><%= link_to 'Home', articles_path, class: 'btn btn-lg btn-primary' %></li>
			<li class="nav-item"><%= link_to 'Add Data', new_article_path, class: 'btn btn-lg btn-warning' %></li>
			<li class="nav-item"><%= link_to 'User', new_user_path, class: 'btn btn-lg btn-info' %></li>
			
			
		</ul>
</nav>
<div class="container">
	<div class="content-wrapper">
		<section class="content">
			<div class="row">
				<div class="col-md-12">
					<!-- CONTENT HERE -->
				      <%= yield :list %>
				      <!-- END OF CONTENT -->

					 <h2>Selamat Datang</h2>
				      

				      <!-- Data Artikel -->
				      <table class="table table-striped">
				      	<thead>
				      		<tr>
				      			<th>Username</th>
				      			<th>Email</th>
				      			<th>Password</th>
				      			<th>Action</th>
				      		</tr>
				      	</thead>
				      	<tbody>
				      		<% @user.each do |user| %>
				      		<tr>
				      			<td><%= article.username %></td>
				      			<td><%= article.email %></td>
				      			<td><%= article.password %></td>
				      			<td></td>
	   				       <% end %>
				      		</tr>
				      	</tbody>
				      </table>
				      
				      	
				     
				</div>
			</div>
		</section>
	</div>
</div>
	
  
</body>
</html>

app/views/users/new.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="nav navbar-nav">
      <li class="nav-item"><%= link_to 'Home', articles_path, class: 'btn btn-lg btn-primary' %></li>
      <li class="nav-item"><%= link_to 'Add Data', new_article_path, class: 'btn btn-lg btn-warning' %></li>
      <li class="nav-item"><%= link_to 'User', new_user_path, class: 'btn btn-lg btn-info' %></li>
    </ul>
</nav>
<div class="container">
  <div class="content-wrapper">
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <!-- CONTENT HERE -->
          <!-- END OF CONTENT -->

           <h2>Selamat Datang</h2>
           <h5>Tambah Data Users</h5>
                <%= form_for (@user) do |f| %>
                <div class="form-group">
                  <%= f.label :username %>
                  <%= f.text_field :username, class: 'form-control' %>
                  <%= @user.errors[:username].first unless @user.errors[:username].blank? %>

                  
                </div>
                <div class="form-group">
                  <%= f.label :email %>
                  <%= f.text_field :email, class: 'form-control' %>
                  <%= @user.errors[:email].first unless @user.errors[:email].blank? %>
                  
                </div>

                <div class="form-group">
                  <%= f.label :password %>
                  <%= f.password_field :password, class: 'form-control' %>
                  <%= @user.errors[:password].first unless @user.errors[:password].blank? %>
                </div>

                <div class="form-group">
                  <%= f.label :humanizer_answer, @user.humanizer_question %>
                <%= f.text_field :humanizer_answer, class: 'form-control' %>
                <%= f.hidden_field :humanizer_question_id %>  
                </div>
                
                <div class="form-group">
                    <%= f.submit :submit %>
                </div>
                <% end %>

        </div>
      </div>
    </section>
  </div>
</div>






  